Vagrant.configure(2) do |config|
    
    #Distro a utilizar por las maquinas
    config.vm.box = "alpine/alpine64"

    #Destino desde donde se busca la imagen a descargar.
    config.vm.box_url = "https://app.vagrantup.com/alpine/boxes/alpine64"

    #Namespace de la primera maquina
    config.vm.define "lugonzalS" do |control|
        #Networking -> https://developer.hashicorp.com/vagrant/docs/networking
        control.vm.hostname = "lugonzalS"
        #habilita como direccion publica la direccion ip
        control.vm.network "public_network", ip: "192.168.56.110", hostname: true
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "lugonzalS"]
            v.memory = 512
            v.cpus = 1
        end

        control.ssh.username = "lugonzal"
        control.ssh.private_key_path = "tools/lugonzalS"

        control.vm.provision "shell", path: "tools/lugonzalS-entrypoint.sh"
    end
    
    #config.vm.define "lugonzalSW" do |control|
    #    control.vm.hostname = "wilSW"
    #    control.vm.network "public_network", ip: "192.168.56.111", hostname: true
    #    control.vm.provider "virtualbox" do |v|
    #        v.customize ["modifyvm", :id, "--name", "lugonzalSW"]
    #        v.memory = 512
    #        v.cpus = 1
    #    end

    #    control.ssh.username: "lugonzal"
    #    control.ssh.private_key_path: "./p1/tools/lugonzalSW"

    #    config.vm.provision "shell", inline: <<-SHELL

    #    SHELL
    #    control.vm.provision "shell", path: REDACTED
    #end
end